### ISSUE TITLE
خطا پس از بروز رسانی به 1.3.0

### ISSUE THREAD

**Issue by Hameds** [Text-Mining/android-app#15]
<div dir="rtl">

کافه‌بازار در بازبینی نسخه 1.3.0 نظر زیر را به عنوان باگ، ارسال کرده است

برنامه هنگام ورود به حساب کاربری یا ثبت‌نام با پیغام "Force close" بسته می‌شود.

مشخصات دستگاه: Huawei P8lite با اندروید نسخهٔ 6

</div>

**Comment by bkhezry** [comment]
<div dir="rtl">
خطاش مربوط به Proguard بود. بخاطر اینکه عباس بتونه با اندروید استدیو نسخه پایدار بازش کنه نسخه پلاگین‌های گردل رو آوردم پایین. شاید به همین خاطر بوده که توابع مربوط به رتروفیت رو حذف می‌کرد.
خطا رو رفع کردم. داره نسخه ۱.۳.۱ ساخته میشه. تموم شد تستش می‌کنم، اگه مشکلی نبود بفرست دوباره به کافه‌بازار
</div>

**Comment by bkhezry** [comment]
حل شده.
